name: Build

on:
  pull_request:
#    branches: [ production ]
    branches: [ feature/289-deploy ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml -P build-for-docker

      - name: Build the docker image
        run: docker build . --file docker/Dockerfile --tag ${{ secrets.TAG }}:latest