name: 'Deploy'

on:
  push:
    branches: [ feature/289-deploy ]

jobs:
  deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout project
          uses: actions/checkout@v2

        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'
            server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

        - name: Build with Maven
          run: mvn -B clean package --file pom.xml -P build-for-docker

        - name: Build the docker image
          run: docker build . --file docker/Dockerfile --tag ${{ secrets.TAG }}:latest

        - name: Log in to Quay registry
          uses: docker/login-action@v1
          with:
            registry: ${{ secrets.QUAY_REGISTRY }}
            username: ${{ secrets.QUAY_USERNAME }}
            password: ${{ secrets.QUAY_TOKEN }}

        - name: Build and push the Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Docker/Dockerfile
            push: true
            tags: ${{ secrets.TAG }}:latest
