
on:
  [push]

jobs:
  test-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{github.workspace}}

      - name: Set up node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Install Dependencies
        run: cd ./frontend && npm ci

      - name: Build frontend with Angular
        run: cd ./frontend && npm run build:staging

      - name: Build backend with Maven
        run: mvn -B clean package --file pom.xml -P staging

      - name: Log in to Quay registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.QUAY_REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build the docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          tags: ${{ secrets.TAG }}:${{ steps.store-version.outputs.version}}-STAGING
          load: true
          push: false

      - name: Run docker image
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.TAG }}:${{ steps.store-version.outputs.version}}-STAGING


      - name: Cypress run e2e tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          start: npm start
          wait-on: 'http://localhost:8080/config'
          wait-on-timeout: 120
          browser: chrome

      - name: Push the docker image
        run: docker push ${{ secrets.TAG }}:${{ steps.store-version.outputs.version}}-STAGING