name: E2E Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
      - name: npm install
        run: cd ./frontend && npm ci
      - name: Run frontend
#        uses: cypress-io/github-action@v5
#        with:
        run: cd ./frontend && npm run build
      - name: Run cypress
        run: cd ./frontend && npm run cypress:run