on:
  [push]

jobs:
  test-and-push:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pwd
          POSTGRES_DB: okr
    steps:
      - uses: actions/checkout@v3
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://postgres:5432/okr
          user: user
          password: pwd
          locations: "./backend/src/main/resources/db/migration, ./backend/src/main/resources/db/data-migration"

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{github.workspace}}

      - name: Set up node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Install Dependencies
        run: cd ./frontend && npm ci

      - name: Build frontend with Angular
        run: cd ./frontend && npm run build:staging

      - name: Build backend with Maven
        run: mvn -B clean package --file pom.xml -P staging

      - name: Build the docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          tags: okr-e2e-test:latest
          load: true
          push: false

      - name: Run docker image
        run: docker run --network=host  -p 8080:8080 okr-e2e-test:latest &

      - name: Cypress run e2e tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          wait-on: 'http://localhost:8080/config'
          wait-on-timeout: 120
          browser: chrome
          working-directory: frontend
          config: baseUrl=http://localhost:8080